{"uuid":"e423f670-a2bc-4641-a5b8-78389873a440","historyId":"c72bffcef293e1d5d8397911dfdc3ae","fullName":"com.qa.opencart.tests.ProductinfoPageTest.productSearchHeaderTest","labels":[{"name":"package","value":"com.qa.opencart.tests.ProductinfoPageTest"},{"name":"testClass","value":"com.qa.opencart.tests.ProductinfoPageTest"},{"name":"testMethod","value":"productSearchHeaderTest"},{"name":"parentSuite","value":"TestNG Regression Suite"},{"name":"suite","value":"Product Info Page Test"},{"name":"subSuite","value":"com.qa.opencart.tests.ProductinfoPageTest"},{"name":"host","value":"DESKTOP-4SB3EJM"},{"name":"thread","value":"7492@DESKTOP-4SB3EJM.TestNG-tests-3(39)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"productSearchHeaderTest","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'DESKTOP-4SB3EJM', ip: '192.168.2.17'","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'DESKTOP-4SB3EJM', ip: '192.168.2.17'\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:152)\r\n\tat com.qa.opencart.factory.DriverFactory.initRemoteDriver(DriverFactory.java:138)\r\n\tat com.qa.opencart.factory.DriverFactory.initDriver(DriverFactory.java:91)\r\n\tat com.qa.opencart.base.BaseTest.setup(BaseTest.java:46)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\r\n\tat org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:657)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:646)\r\n\tat org.testng.TestRunner.run(TestRunner.java:612)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\nCaused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.29.0', revision: '5fc1ec94cb'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'\nDriver info: driver.version: RemoteWebDriver\r\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:424)\r\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)\r\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)\r\n\tat org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)\r\n\t... 22 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)\r\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\r\n\t... 3 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"MacBook Pro"},{"name":"browser","value":"edge"},{"name":"arg0","value":"macbook"}],"start":1744908274971,"stop":1744908274972}