<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4SB3EJM" failures="1" tests="9" name="com.qa.opencart.tests.ProductinfoPageTest" time="13.366" errors="0" timestamp="2025-04-17T12:58:17 EDT" skipped="0">
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productImagesCountTest" time="1.349"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productInfoTest" time="1.705">
    <failure message="The following asserts failed:
	expected [In Stock] but found [Out Of Stock]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [In Stock] but found [Out Of Stock]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.qa.opencart.tests.ProductinfoPageTest.productInfoTest(ProductinfoPageTest.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- productInfoTest -->
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productImagesCountTest" time="2.029"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productImagesCountTest" time="1.674"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productSearchHeaderTest" time="1.084"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productImagesCountTest" time="1.442"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productSearchHeaderTest" time="1.074"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productImagesCountTest" time="1.739"/>
  <testcase classname="com.qa.opencart.tests.ProductinfoPageTest" name="productSearchHeaderTest" time="1.270"/>
</testsuite> <!-- com.qa.opencart.tests.ProductinfoPageTest -->
