<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4SB3EJM" failures="1" tests="9" name="com.qa.opencart.tests.LoginPageTest" time="8.704" errors="0" timestamp="2025-04-17T15:37:10 EDT" skipped="0">
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="5.288">
    <failure message="==title is not matched expected [Account Login11] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ==title is not matched expected [Account Login11] but found [null]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.qa.opencart.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="footerTest" time="0.423"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageURLTest" time="0.026"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="footerTest" time="0.519"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="logoTest" time="0.047"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="footerTest" time="0.332"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="footerTest" time="0.377"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="forgotPwdLinkExistTest" time="0.292"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginTest" time="1.400"/>
</testsuite> <!-- com.qa.opencart.tests.LoginPageTest -->
